version: '3'
services:
  meteor: # TODO: criar script que pode ser corrido dentro deste container para recriar o meteor sem ter de fazer build à imagem, dado que o src está atualizado com o volume /opt/meteor/src
    build:
      context: ./meteor/
    ports:
      - "3010:3000"
    links:
      - mongo
      - api
    # volumes:
      # - ./:/opt/meteor/src
    env_file:
      - .env
  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    volumes:
      - ./data/db:/data/db # TODO: garantir persistência da DB
    ports:
      - "27017:27017"
  api:
    build:
      context: ./api/
    ports:
      - "8081:8080" # if access id needed from the outside (otherwise no need)